# Generated by Django 5.0.7 on 2024-08-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('empid', models.CharField(max_length=40)),
                ('cname', models.CharField(max_length=60)),
                ('cdesg', models.CharField(max_length=70)),
                ('salary', models.FloatField()),
                ('pic', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
