# Generated by Django 4.1 on 2024-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdno', models.IntegerField()),
                ('sname', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=40)),
                ('Eductn', models.CharField(max_length=40)),
                ('mark', models.FloatField()),
                ('img', models.ImageField(upload_to='static/profile')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(upload_to='static/upload/'),
        ),
    ]
