# Generated by Django 4.1 on 2024-08-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptapp', '0002_student_alter_employee_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=70)),
                ('price', models.FloatField()),
                ('pqty', models.IntegerField()),
                ('desc', models.CharField(max_length=75)),
                ('review', models.IntegerField()),
                ('cname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
    ]
