# Generated by Django 4.1 on 2024-08-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptapp', '0004_customer_remove_product_address_remove_product_cname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ormdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=80)),
            ],
        ),
    ]
