# Generated by Django 4.1 on 2024-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptapp', '0005_ormdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormdata',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
